### PR TITLE
fix(recommendation): add app id to the default config

### PR DESCRIPTION
**Pull request by oneslash**
chore(travis): add go 1.14

| Q                 | A
| ----------------- | ----------
| Bug fix?          | yes
| New feature?      | no    
| BC breaks?        | no     
| Related Issue     | 
| Need Doc update   | no

## Describe your change
Adding Go 1.14 to the travis.

## What problem is this fixing?
Adding AppId to the recommendation constructor

### CODE REVIEW

**Comment by oneslash** [comment]
@aseure thanks done

**Comment by aseure** [comment]
@oneslash thanks a lot! One last thing, could you please squash your two commits into a single one?

**Comment by oneslash** [comment]
@aseure done!

**Comment by aseure** [comment]
Thanks a lot for your contribution @oneslash !

**Pull request merged**
