### PR TITLE
Tests: replace glide with Dep and fix typos

### PR DESCRIPTION
**Pull request by julienbourdeau**

### CODE REVIEW

**Comment by aseure** [comment]
Cool changes, thank you for taking care of those @julienbourdeau.

As you've asked, and it may be assimilated in this PR, you could also add `go get -u github.com/rakyll/gotest` in the Travis file and change the `make test` Makefile rule to use `gotest` instead of `go test` (drop-in replacement) to have the colored output.

**Comment by julienbourdeau** [comment]
I couldn't find details about supported Go versions for `gotest`, I hope it will be good 🤞

**Comment by julienbourdeau** [comment]
All tests are green ✅ 🎉

**Comment by aseure** [comment]
LGTM 👍 Thank you @julienbourdeau

**Pull request merged**
