### PR TITLE
Make requests with body in the Suggestions API work

### LINKED ISSUE #758: Unable to Create/Update suggestion index configuration
- Algolia Client Version: 3.31.1
- Language Version: 1.22

### Description
When trying to create or update a suggestion index configuration, we get an error saying that the JSON response body could not be deserialized.
Our api key has the correct ACLs according to the documentation. We even tried with granting it all rights and still get the same error.

image

### Steps To Reproduce
```go
suggestionsClient := suggestions.NewClient(appID, apiKey)

minHits := 2
minLetters := 2

config := suggestions.IndexConfiguration{
	IndexName: "test_query_suggestions",
	SourceIndices: []suggestions.SourceIndex{
		{
			IndexName:  "test",
			MinHits:    &minHits,
			MinLetters: &minLetters,
		},
	},
	Languages: suggestions.BoolOrStringArray{
		IsBool:      false,
		StringArray: []string{language},
	},
}

err := suggestionsClient.CreateConfig(config, opt.ExposeIntermediateNetworkErrors(true))
```

We hit this breakpoint in transport.go in the Algolia code:
image
The response body looks like it is empty and unmarshalling the empty body fails?

image

The calls `suggestionsClient.ListConfigs()` and `suggestionsClient.GetConfig()` do work, so we know the setup of the client works.

**Update:**
The real error is not the parsing of the response body, but it goes wrong earlier.
We get a 307 response from the POST endpoint: 
image

Things seem to go wrong in the wrapJSONEncoder function.

### PR DESCRIPTION
**Pull request by andersaction**
| Q                 | A
| ----------------- | ----------
| Bug fix?          | yes
| New feature?      | no 
| BC breaks?        | no     
| Related Issue     | Fix #758 
| Need Doc update   | no

## Describe your change
This change in the `wrapJSONEncoder` function makes the POST and PUT calls in the Suggestions API work without failure.

Interestingly other calls with a body from the search client like MultipleQueries work fine using the old `wrapJSONEncoder`, which leads me to think that the problem might be in the struct IndexConfiguration, which is the body of our failing calls.
image

Either way this change seems to work for both calls from suggestions client and search client.

## What problem is this fixing?
As described in the issue, CreateConfiguration and UpdateConfiguration does not work for us: 
https://www.algolia.com/doc/rest-api/query-suggestions/#create-a-configuration
https://www.algolia.com/doc/rest-api/query-suggestions/#update-a-configuration

### CODE REVIEW

**Review by nicknijenhuis — APPROVED** [review]
LGTM!

**Review by shortcuts — COMMENTED** [review]
The solution seems to work however I believe the pipe implementation allows more robust memory allocation

It seems like the underlying issue you highlight here https://github.com/algolia/algoliasearch-client-go/issues/758 is just that the response is empty, no? In that case we can maybe early return if `in` is nil?

cc @Nagriar if you remember the reason why we picked this implem

**Comment by shortcuts** [comment]
(Thanks for taking the time to investigate btw!!)

**Comment by hernanif1** [comment]
Hi @shortcuts, I've been working with @andersaction to implement this PR

before:
```go
	pr, pw := io.Pipe()
	go func() {
		errEncode := json.NewEncoder(pw).Encode(in) // in is not empty but the pr return body 0
	...
```

even when `in` has content, this code is not parsing the body correctly resulting the `pr` with body 0 

I don't see how an earlier return could help in that case.
But I imagine that this code works for you. 

I wonder if it is our Go Lang version 1.22 that might handle the io.Pipe differently than 1.13.

**Comment by shortcuts** [comment]
> Hi @shortcuts, I've been working with @andersaction to implement this PR
> 
> before:
> 
> ```go
> 	pr, pw := io.Pipe()
> 	go func() {
> 		errEncode := json.NewEncoder(pw).Encode(in) // in is not empty but the pr returns body 0
> 	...
> ```
> 
> even when `in` has content, this code is not parsing the body correctly resulting the `pr` with body 0
> 
> I don't see how an earlier return could help in that case. (or I didn't get it, also possible)
> 
> But I imagine that this code (current code without modification) works for you. I wonder if it is our Go Lang version 1.22 that might handle the io.Pipe differently than 1.13.

Oh ok I thought it was empty, I did not tried to reproduce the error yet but for the next major version of the client (available on https://github.com/algolia/algoliasearch-client-go/tree/next) we've went with a similar approach so I'd like to know if there was motivations to use Pipe in the past

**Comment by hernanif1** [comment]
@shortcuts I'll install the "next" version tomorrow and I'll let you know, I'm not sure if it will work smoothly, so let's see 😅

**Comment by shortcuts** [comment]
> @shortcuts I'll install the "next" version tomorrow and I'll let you know, I'm not sure if it will work smoothly, so let's see 😅

yup there is a pretty huge number of breaking changes.. you can find the docs for the beta here https://api-clients-automation.netlify.app/ if you want, but I'll follow up with this PR asap too :)

**Comment by andersaction** [comment]
> The solution seems to work however I believe the pipe implementation allows more robust memory allocation
> 
> It seems like the underlying issue you highlight here #758 is just that the response is empty, no? In that case we can maybe early return if `in` is nil?
> 
> cc @Nagriar if you remember the reason why we picked this implem

At first I thought the problem was with the empty response, but upon further investigation it seems like it goes wrong already when serializing the request body to JSON. 

Since other POST calls from other clients work, I wonder if there could be something wrong with the `IndexConfiguration` struct itself (or `SourceIndex` or `BoolOrStringArray`) in combination with the implementation of `wrapJSONEncoder`.

**Comment by hernanif1** [comment]
Hi @shortcuts, just to let you know that we are handling the config manually, so we are covered for now, but updating them manually is a nightmare 😅. So no big rush, but please notify me when you have a forecast of a possible date to have a look, if you need additional information or some concerns about this so we can update it.  Glad to help. 😀

**Comment by shortcuts** [comment]
(Sorry for the delay I had a lot of stuff to tackle)

Hey! So I've tried some stuff with the client in order to reproduce the error and couldn't make it fail, but then I saw you mention 307 redirect not being caught and then I managed to make the request fail by misconfiguring (or leaving the default, `US`, value) my region.

My app region is in `EU` (as is yours), when I try to call the client with no region set (defaults to `US`), I get `panic: all hosts have been contacted unsuccessfully, it can either be a server or a network error or wrong appID/key credentials were used. You can use opt.ExposeIntermediateNetworkErrors(true) to investigate.`, but when I properly set it to `EU` I can call the API to create/update config without issue

Would you letting me know if defining the region works for you? or if not, what is the error you exactly get from the API call?

Below is attached the program I've ran, `testQs` should match your implem I believe

```go
package main

import (
	"fmt"

	"github.com/algolia/algoliasearch-client-go/v3/algolia/opt"
	"github.com/algolia/algoliasearch-client-go/v3/algolia/region"
	"github.com/algolia/algoliasearch-client-go/v3/algolia/suggestions"
)

func testQs() int {
	client := suggestions.NewClientWithConfig(suggestions.Configuration{
		AppID:  "QPBQ67WNIG",
		APIKey: "",
		Region: region.EU,
	})

	minHits := 2
	minLetters := 2

	config := suggestions.IndexConfiguration{
		IndexName: "testbar",
		SourceIndices: []suggestions.SourceIndex{
			{
				IndexName:  "api-clients-automation",
				MinHits:    &minHits,
				MinLetters: &minLetters,
			},
		},
		Languages: suggestions.BoolOrStringArray{
			IsBool:      false,
			StringArray: []string{"en"},
		},
	}

	err := client.CreateConfig(config, opt.ExposeIntermediateNetworkErrors(true))
	if err != nil {
		panic(err)
	}

	return 0
}
```

**Comment by andersaction** [comment]
@shortcuts thanks for diving into it. Setting the region to EU seems to fix the issue indeed. Sorry for missing that. Closing this PR and the issue.

A nice improvement would be if the suggestions api documentation [https://www.algolia.com/doc/rest-api/query-suggestions/](https://www.algolia.com/doc/rest-api/query-suggestions/) is updated with examples for the Go client (and other clients), like the excellent documentation for the search client :)

**Comment by shortcuts** [comment]
> @shortcuts thanks for diving into it. Setting the region to EU seems to fix the issue indeed. Sorry for missing that. Closing this PR and the issue.

Glad it solved your issue!

> A nice improvement would be if the suggestions api documentation https://www.algolia.com/doc/rest-api/query-suggestions/ is updated with examples for the Go client (and other clients), like the excellent documentation for the search client :)

The new major version aims at making this clearer, hopefully the doc will help too!

> Still very strange that our "fix" in this PR made things work even with the wrong region configured by the way 🤯

yup that's weird 🤔 I guess this has to be something related with the 307 response, I'll ask the team in charge of that API if they redirect based on the app region

**Pull request closed without merging**
