### PR TITLE
feat(monitoring): add new monitoring api

### PR DESCRIPTION
**Pull request by oneslash**
fix(recommendation): fix app id not setup

| Q                 | A
| ----------------- | ----------
| Bug fix?          | no
| New feature?      | yes  
| BC breaks?        | no     
| Related Issue     | 
| Need Doc update   | yes

## Describe your change
Adding monitoring API, later if accepted will add more endpoints

## What problem is this fixing?
Fixing App ID not being passed to recommendations

### CODE REVIEW

**Comment by oneslash** [comment]
I have run tests with my Algolia credentials and they are passing:

```
sardorbek.pulatov@mbp-231 algoliasearch-client-go % ALGOLIA_APPLICATION_ID_1=xxx ALGOLIA_ADMIN_KEY_MCM=xxx go test -v ./cts/monitoring
=== RUN   TestGetCurrentApiStatus
=== PAUSE TestGetCurrentApiStatus
=== RUN   TestGetCurrentServerStatus
=== PAUSE TestGetCurrentServerStatus
=== CONT  TestGetCurrentApiStatus
=== CONT  TestGetCurrentServerStatus
--- PASS: TestGetCurrentApiStatus (2.21s)
--- PASS: TestGetCurrentServerStatus (2.22s)
PASS
ok      github.com/algolia/algoliasearch-client-go/v3/cts/monitoring    2.317s
```

**Comment by oneslash** [comment]
I have run tests with my Algolia credentials and they are passing:

It would be great if you can add monitoring key into the travis env

```
$ ALGOLIA_APPLICATION_ID_1=xxx ALGOLIA_ADMIN_KEY_MCM=xxx go test -v ./cts/monitoring
=== RUN   TestGetCurrentApiStatus
=== PAUSE TestGetCurrentApiStatus
=== RUN   TestGetCurrentServerStatus
=== PAUSE TestGetCurrentServerStatus
=== CONT  TestGetCurrentApiStatus
=== CONT  TestGetCurrentServerStatus
--- PASS: TestGetCurrentApiStatus (2.21s)
--- PASS: TestGetCurrentServerStatus (2.22s)
PASS
ok      github.com/algolia/algoliasearch-client-go/v3/cts/monitoring    2.317s
```

**Comment by aseure** [comment]
Hello @oneslash, and thank you very much for this contribution.

While there's not much to say about the PR itself, everything looks good and clean; we'll have to pause it for now, here are the reasons for that:

1. this endpoint is Enterprise-only, and so far we've tried to keep our API clients features available for all users;
2. we first need to assess the need for adding a new endpoint to all our API clients (when implementing features and bug fixes, we do it across our 11 API clients);
3. we need to check with the team responsible for the monitoring API if they want to expose it in our API clients and what could be the impact for them.

Hopefully, we'll back to you in the next few days with more information and guidelines regarding what should and shouldn't be implemented.

Thank you in advance for your patience and understanding on this!

**Comment by oneslash** [comment]
@aseure thank you very much for review, regarding recommendation api fix, I would create another PR

**Comment by aseure** [comment]
@oneslash thank you for splitting the changes into different PRs.

I got the feedback both from my team and the team responsible for the Monitoring API. They all confirmed that for the reasons I've mentioned before, we will not be able to move forward with your proposal of implementing part or all of the Monitoring endpoints. To be totally transparent with you, those endpoints are now quite old, and the metrics they expose can be quite misleading if poorly documented. If we ever plan to expose those metrics in the future, it would probably be via different, new endpoints.

I'm sorry to leave you with an unmerged PR after the time you have put implementing this feature in a very idiomatic way. At least, I hope it helped you discover the code base and that it will be easier for you to contribute in the future. Next time, to prevent you from doing all the hard work, don't hesitate to open an issue for us to discuss it together.

Thank you for your understanding!

**Comment by oneslash** [comment]
I totally understand, thank you very much for taking time to review and clarify.

**Pull request closed without merging**
