### PR TITLE
Search result struct

### PR DESCRIPTION
**Pull request by csquared**
This creates a struct for a `SearchResult` so we don't have to keep doing the parsing into `map[string]interface{}` or just `interface{}`, which should be avoided anyways. 

It really cleans up the search code!

See: https://github.com/usecanvas/canvas-cli/commit/f335b461f5739710ab6c721231b004ed5e9ba2c9

### CODE REVIEW

**Comment by csquared** [comment]
Note: this is "stacked" on top of: https://github.com/algolia/algoliasearch-client-go/pull/6

**Comment by vvo** [comment]
Seems legit, every go project should be gofmt, thoughts @Nagriar ?

**Comment by vvo** [comment]
@csquared great, can you rebase on master so that we only have the relevant commit now? Thx

**Comment by Nagriar** [comment]
Thanks @csquared,

I agree it's really easier to use a structure than a `interface{}` but the structure of the json can change and new attributes can be added or for exemple when you pass the query parameter `getRankingInfo=1`, you can retrieve a lot information. So I prefer to keep both the search with interface{} and the search with the structure for the common use.

You modification in Transport.go will affect all API call we should have a different handling for the `search` method and for the other calls.

**Comment by csquared** [comment]
@Nagriar Great point -> I never should have made this the default return type for all requests! Whoops!

So are you proposing two endpoints, one that returns an `inteface{}` and one that returns a `struct`? 

Personally, I'd say to just figure out what the full response looks like and make a struct that handles it, leaving fields that did not get returned initialized to their empty state.  Ie: I'd still rather do `if result.Key != ""` than `if result.Key.(string)`.

Anyways, lemme know what you think about the above choices.

**Comment by csquared** [comment]
Going to close and will let you know what I wind up doing w. this.

**Pull request closed without merging**
